### ISSUE TITLE
Password character :

### ISSUE THREAD

**Issue by ernesst** [ubports/account-plugins#8] opened 2018-05-28 04:03 UTC
If using : in my password I cannot log in.
Removing the : in the password does the trick. 

Not urgent, but to keep in mind to advise users... in order to avoid frustration.

**Comment by jonnius** [comment] 2018-08-09 04:20
Do you mean nextcloud? This is a duplicate of ubports/ubuntu-touch#468.

**Comment by ernesst** [comment] 2018-08-11 20:08
Yes it's related.

**Comment by Flohack74** [comment] 2018-09-08 14:10
Resolved by https://github.com/ubports/account-plugins/pull/16

**Closed as completed by Flohack74** 2018-09-08 14:10 UTC
Labels: bug
